version: '3.8'

services:
  mysql-db:
    image: mysql:5.7.23
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saas
      MYSQL_USER: admin
      MYSQL_PASSWORD: mockupsaa
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-saas:
    build: ./api-saas
    container_name: api-saas
    restart: unless-stopped
    ports:
      - "5005:5000"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: admin
      DB_PASSWORD: mockupsaa
      DB_NAME: saas

volumes:
  db_data:
